# Generated by Django 5.0.6 on 2024-06-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_teacher_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
