# Generated by Django 5.0.6 on 2024-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_subject_student_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_assigned',
            field=models.CharField(default='Unassigned', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='playground.subject'),
        ),
    ]
