# Generated by Django 5.0.6 on 2024-06-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_student_options_teacher_grade_assigned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade'], 'verbose_name_plural': 'Students'},
        ),
    ]
