# Generated by Django 5.0.6 on 2024-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_student_admno_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, to='playground.student'),
        ),
    ]
